# Generated by Django 6.0.5 on 2026-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Document', 'Document'), ('Accessory', 'Accessory'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('date_lost', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Found', 'Found'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('reward', models.IntegerField(default=0)),
            ],
        ),
    ]
