# Generated by Django 6.0.5 on 2026-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Document', 'Document'), ('Accessory', 'Accessory'), ('Wallet', 'Wallet'), ('Keys', 'Keys'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Document', 'Document'), ('Accessory', 'Accessory'), ('Wallet', 'Wallet'), ('Keys', 'Keys'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=50),
        ),
    ]
