# Generated by Django 6.0.5 on 2026-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_founditem_category_alter_lostitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_items/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Claim Pending', 'Claim Pending'), ('Resolved', 'Resolved')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Claim Pending', 'Claim Pending'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
    ]
