# Generated by Django 6.0.5 on 2026-06-25 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claim_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='founditem',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_found_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
