# Generated by Django 6.0.5 on 2026-06-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_founditem_claim_accepted_founditem_claimant'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claimed_lost_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lostitem'),
        ),
    ]
